### ISSUE TITLE
Does not work with windows path separators

### ISSUE THREAD

**Issue by Mitjan11** [adjohnson916/is-npm-not-yarn#2]
`process.env.npm_execpath` in windows environments returns the path with a backslash separator for the path, instead of a forward slash like on unix systems. Because there's an explicit check for a forward slash, this package doesn't function on windows environments.

Maybe it's a good idea to normalize the paths using the [slash](https://www.npmjs.com/package/slash) package?

**Comment by AndersDJohnson** [comment]
@Mitjan11 Thanks for reporting. Did not test on Windows. @chilijung do you think it would be sufficient to check if the env var exists at all?

**Comment by chilijung** [comment]
@AndersDJohnson Sorry I don't get it, why should we check the env variable exists?  In this case, `slash(process.env.npm_execpath)` might just fix the problem on windows (haven't test yet).

oh, I get it.  I think `npm_execpath` is now the most reliable solution to check (https://stackoverflow.com/questions/41076172/force-yarn-install-instead-of-npm-install-for-node-module) but it is not documented so it might change in the future.

**Comment by AndersDJohnson** [comment]
@Mitjan11 @chilijung Thanks for the tip to use `slash`. I've published the fix to npm with `>2.0.2`. I didn't test it on Windows yet, so please let me know if you get a chance to do so.

**Comment by Mitjan11** [comment]
@AndersDJohnson I just tested it on Windows 10 and it's working perfectly.

Any idea when the use-yarn package could be updated to include this change, or should I make an issue for it there?

**Comment by AndersDJohnson** [comment]
@Mitjan11 Thanks for testing. Glad it works. I've just published a new version of [`use-yarn`](https://www.npmjs.com/package/use-yarn) that uses the updated version here.

FYI @chilijung
